'use client'

import '@/styles/globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import styles from '@/styles/global.module.css'
import {Footer} from "@/components/Primary/Layout/Footer/Footer";
import {GameMenu} from "@/components/Primary/Layout/GameMenu/GameMenu";
import {Header} from "@/components/Primary/Layout/Header/Header";

const inter = Inter({subsets: ['latin']})

const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={inter.className} style={{width: '100%'}}>
        <div className={`${styles.wrapper}`}>
            <GameMenu/>
            <div className={`${styles.main}`}>
                <Header/>
                {/* <Chat/> */}
                {children}
                <div style={{backgroundColor: '#191C26', width: '100%'}}>
                    <Footer/>
                </div>
            </div>
        </div>
        </body>
        </html>
    )
}