'use client'

import '../css/global.module.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import styles from '../css/global.module.css'
import {Footer} from "@/components/Layout/Footer/Footer";
import {GameMenu} from "@/components/Layout/GameMenu/GameMenu";
import {Header} from "@/components/Layout/Header/Header";

const inter = Inter({subsets: ['latin']})

const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <div className={`${styles.wrapper}`}>
            <GameMenu/>
            <div className={`${styles.main}`}>
                <Header/>
                {/* <Chat/> */}
                {children}
                <Footer/>
            </div>
        </div>
        </body>
        </html>
    )
}
